### ISSUE TITLE
[Bug] Agent error abort

### ISSUE THREAD

**Issue by YouZhengChuan** [open-falcon/agent#88]
OS：Linux my-vm-01 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

在虚拟机上跑了一天，第二天看挂了，日志里面留下如下错误日志
```
2017/05/16 14:02:48 rpc.go:44: dial 192.168.1.150:8433 fail: dial tcp 192.168.1.150:8433: getsockopt: connection refused
2017/05/16 14:02:50 rpc.go:44: dial 192.168.1.150:8433 fail: dial tcp 192.168.1.150:8433: getsockopt: connection refused
2017/05/16 14:02:54 rpc.go:44: dial 192.168.1.150:8433 fail: dial tcp 192.168.1.150:8433: getsockopt: connection refused
2017/05/16 14:03:02 rpc.go:44: dial 192.168.1.150:8433 fail: dial tcp 192.168.1.150:8433: getsockopt: connection refused
2017/05/16 14:03:18 rpc.go:44: dial 192.168.1.150:8433 fail: dial tcp 192.168.1.150:8433: getsockopt: connection refused
2017/05/16 14:03:50 rpc.go:44: dial 192.168.1.150:8433 fail: dial tcp 192.168.1.150:8433: getsockopt: connection refused
2017/05/16 14:04:54 var.go:65: <= <Total=95, Invalid:0, Latency=2ms, Message:ok>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x71ef12]

goroutine 24 [running]:
github.com/open-falcon/agent/g.(*SingleConnRpcClient).Call(0x0, 0x85f88f, 0xf, 0x7bcf40, 0xc4200af1a0, 0x7df660, 0xc4204c6c60, 0x0, 0x0)
        /Users/youzhengchuan/go/src/github.com/open-falcon/agent/g/rpc.go:58 +0x52
github.com/open-falcon/agent/g.updateMetrics(0xc4200e8e00, 0x12, 0xc420230fc0, 0x6, 0x8, 0xc4204c6c60, 0xc42004c000)
        /Users/youzhengchuan/go/src/github.com/open-falcon/agent/g/transfer.go:50 +0x153
github.com/open-falcon/agent/g.SendMetrics(0xc420230fc0, 0x6, 0x8, 0xc4204c6c60)
        /Users/youzhengchuan/go/src/github.com/open-falcon/agent/g/transfer.go:24 +0x14e
github.com/open-falcon/agent/g.SendToTransfer(0xc420230fc0, 0x6, 0x8)
        /Users/youzhengchuan/go/src/github.com/open-falcon/agent/g/var.go:60 +0x203
github.com/open-falcon/agent/cron.collect(0x3c, 0xc4200eb090, 0x2, 0x2)
        /Users/youzhengchuan/go/src/github.com/open-falcon/agent/cron/collector.go:73 +0x3d6
created by github.com/open-falcon/agent/cron.Collect
        /Users/youzhengchuan/go/src/github.com/open-falcon/agent/cron/collector.go:30 +0xb2
```

**Comment by laiwei** [comment]
请用 https://github.com/open-falcon/falcon-plus 版本的agent
